# ä»£ç†é›†åˆï¼ˆè·å–æœºåœºè®¢é˜…é“¾æ¥å†…çš„æ‰€æœ‰èŠ‚ç‚¹ï¼‰
proxy-providers:
  ğŸ›« æœºåœºè®¢é˜… 1:
    type: http
    # æœºåœºè®¢é˜…é“¾æ¥ï¼Œä½¿ç”¨ Clash é“¾æ¥
    url: "https://example.com/xxx/xxx&flag=clash"
    path: ./proxies/airport1.yaml
    interval: 86400
    # åˆæ­¥ç­›é€‰éœ€è¦çš„èŠ‚ç‚¹ï¼Œå¯æœ‰æ•ˆå‡è½»è·¯ç”±å™¨å‹åŠ›ï¼Œæ”¯æŒæ­£åˆ™è¡¨è¾¾å¼ï¼Œä¸ç­›é€‰å¯åˆ é™¤æ­¤é…ç½®é¡¹
    filter: "(?i)(ğŸ‡­ğŸ‡°|æ¸¯|hk|hongkong|hong kong|ğŸ‡¹ğŸ‡¼|å°|tw|taiwan|tai wan|ğŸ‡¯ğŸ‡µ|æ—¥|jp|japan|ğŸ‡¸ğŸ‡¬|æ–°|sg|singapore|ğŸ‡ºğŸ‡¸|ç¾|us|unitedstates|united states)"
    # åˆæ­¥æ’é™¤ä¸éœ€è¦çš„èŠ‚ç‚¹ï¼Œæ”¯æŒæ­£åˆ™è¡¨è¾¾å¼ï¼Œè‹¥ä¸æ’é™¤å¯åˆ é™¤æ­¤é…ç½®é¡¹
    exclude-filter: "é«˜å€|ç›´è¿|Ã—10"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
    override:
      # ä¸ºèŠ‚ç‚¹åç§°æ·»åŠ å›ºå®šå‰ç¼€ï¼Œå¦‚èŠ‚ç‚¹åç§°åŸä¸ºâ€œé¦™æ¸¯èŠ‚ç‚¹â€ä¼šå˜æˆâ€œğŸ›« æœºåœºè®¢é˜… 1-é¦™æ¸¯èŠ‚ç‚¹â€ï¼›æ¨èæœ‰å¤šä¸ªæœºåœºæ—¶ä½¿ç”¨
      additional-prefix: "ğŸ›« æœºåœºè®¢é˜… 1-"
      # ä¸ºèŠ‚ç‚¹åç§°æ·»åŠ å›ºå®šåç¼€ï¼Œå¦‚èŠ‚ç‚¹åç§°åŸä¸ºâ€œé¦™æ¸¯èŠ‚ç‚¹â€ä¼šå˜æˆâ€œé¦™æ¸¯èŠ‚ç‚¹-ğŸ›« æœºåœºè®¢é˜… 1â€ï¼›æ¨èæœ‰å¤šä¸ªæœºåœºæ—¶ä½¿ç”¨
      additional-suffix: "-ğŸ›« æœºåœºè®¢é˜… 1"

  ğŸ›« æœºåœºè®¢é˜… 2:
    type: http
    url: "https://example.com/xxx/xxx&flag=clash"
    path: ./proxies/airport2.yaml
    interval: 43200
    filter: "(?i)(ğŸ‡­ğŸ‡°|æ¸¯|hk|hongkong|hong kong|ğŸ‡¹ğŸ‡¼|å°|tw|taiwan|tai wan|ğŸ‡¯ğŸ‡µ|æ—¥|jp|japan|ğŸ‡¸ğŸ‡¬|æ–°|sg|singapore|ğŸ‡ºğŸ‡¸|ç¾|us|unitedstates|united states)"
    exclude-filter: "é«˜å€|ç›´è¿|Ã—10"
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
    override:
      # ä¸ºèŠ‚ç‚¹åç§°æ·»åŠ å›ºå®šå‰ç¼€ï¼Œå¦‚èŠ‚ç‚¹åç§°åŸä¸ºâ€œé¦™æ¸¯èŠ‚ç‚¹â€ä¼šå˜æˆâ€œğŸ›« æœºåœºè®¢é˜… 2-é¦™æ¸¯èŠ‚ç‚¹â€ï¼›æ¨èæœ‰å¤šä¸ªæœºåœºæ—¶ä½¿ç”¨
      additional-prefix: "ğŸ›« æœºåœºè®¢é˜… 2-"
      # ä¸ºèŠ‚ç‚¹åç§°æ·»åŠ å›ºå®šåç¼€ï¼Œå¦‚èŠ‚ç‚¹åç§°åŸä¸ºâ€œé¦™æ¸¯èŠ‚ç‚¹â€ä¼šå˜æˆâ€œé¦™æ¸¯èŠ‚ç‚¹-ğŸ›« æœºåœºè®¢é˜… 2â€ï¼›æ¨èæœ‰å¤šä¸ªæœºåœºæ—¶ä½¿ç”¨
      additional-suffix: "-ğŸ›« æœºåœºè®¢é˜… 2"

# å•ä¸ªå‡ºç«™ä»£ç†èŠ‚ç‚¹ï¼ˆä»¥ vless ä¸ºä¾‹ï¼‰
proxies:
  - name: ğŸ†“ å…è´¹èŠ‚ç‚¹
    type: vless
    server: example.com
    port: 443
    uuid: {uuid}
    network: ws
    tls: true
    udp: false
    sni: example.com
    client-fingerprint: chrome
    ws-opts:
      path: "/?ed=2048"
      headers:
        host: example.com

# ç­–ç•¥ç»„
proxy-groups:
  # æ‰‹åŠ¨é€‰æ‹©å›½å®¶æˆ–åœ°åŒºèŠ‚ç‚¹ï¼›æ ¹æ®â€œå›½å®¶æˆ–åœ°åŒºç­–ç•¥ç»„â€åç§°å¯¹ `proxies` å€¼è¿›è¡Œå¢åˆ æ”¹ï¼Œé¡»ä¸€ä¸€å¯¹åº”
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ‘‰ æ‰‹åŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ†“ å…è´¹èŠ‚ç‚¹]}
  # é€‰æ‹©`ğŸ¯ å…¨çƒç›´è¿`ä¸ºæµ‹è¯•æœ¬åœ°ç½‘ç»œï¼ˆè¿è¥å•†ç½‘ç»œé€Ÿåº¦å’Œ IPv6 æ”¯æŒæƒ…å†µï¼‰ï¼Œå¯é€‰æ‹©å…¶å®ƒèŠ‚ç‚¹ç”¨äºæµ‹è¯•æœºåœºèŠ‚ç‚¹é€Ÿåº¦å’Œ IPv6 æ”¯æŒæƒ…å†µ
  - {name: ğŸ“ˆ ç½‘ç»œæµ‹è¯•, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ†“ å…è´¹èŠ‚ç‚¹]}
  - {name: ğŸ¤– AI å¹³å°, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹]}
  - {name: ğŸ“‹ Trackerslist, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ® æ¸¸æˆæœåŠ¡, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸªŸ å¾®è½¯æœåŠ¡, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ‡¬ è°·æ­ŒæœåŠ¡, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ è‹¹æœæœåŠ¡, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸŒ å›½å¤–åª’ä½“, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹]}
  - {name: ğŸ® æ¸¸æˆå¹³å°, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹]}
  - {name: ğŸ›¡ï¸ ç›´è¿åŸŸå, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ€„ï¸ ç›´è¿ IP, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ§± ä»£ç†åŸŸå, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ¯ å…¨çƒç›´è¿]}
  - {name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ†“ å…è´¹èŠ‚ç‚¹]}
  # è‹¥ä½¿ç”¨ ShellCrashï¼Œç”±äºæ— æ³•åˆ¤æ–­æœ¬æœºè¿›ç¨‹ï¼ˆé»˜è®¤ `find-process-mode: off`ï¼‰ï¼Œéœ€åˆ é™¤æ­¤æ¡ `â¬‡ï¸ ç›´è¿è½¯ä»¶`ï¼›è‹¥åœ¨é¢æ¿ Dashboard ä¸­éœ€éšè—è¯¥ç­–ç•¥ç»„ï¼Œå¯æ·»åŠ  `hidden: true` é…ç½®é¡¹
  - {name: â¬‡ï¸ ç›´è¿è½¯ä»¶, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿], hidden: true}
  - {name: ğŸ”’ ç§æœ‰ç½‘ç»œ, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿], hidden: true}
  # è‹¥æœºåœºçš„ UDP è´¨é‡ä¸æ˜¯å¾ˆå¥½ï¼Œå¯¼è‡´æŸæ¸¸æˆæ— æ³•ç™»å½•æˆ–è¿›å…¥æˆ¿é—´ï¼Œå¯æ·»åŠ  `disable-udp: true` é…ç½®é¡¹è§£å†³
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ†“ å…è´¹èŠ‚ç‚¹, ğŸ¯ å…¨çƒç›´è¿]}
  - {name: ğŸ›‘ å¹¿å‘ŠåŸŸå, type: select, proxies: [ğŸ”´ å…¨çƒæ‹¦æˆª, ğŸŸ¢ å…¨çƒç»•è¿‡]}
  - {name: ğŸ”´ å…¨çƒæ‹¦æˆª, type: select, proxies: [REJECT], hidden: true}
  - {name: ğŸŸ¢ å…¨çƒç»•è¿‡, type: select, proxies: [PASS], hidden: true}
  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [DIRECT], hidden: true}

  # ----------------å›½å®¶æˆ–åœ°åŒºç­–ç•¥ç»„---------------------
  # è‡ªåŠ¨é€‰æ‹©èŠ‚ç‚¹ï¼Œå³æŒ‰ç…§ url æµ‹è¯•ç»“æœä½¿ç”¨å»¶è¿Ÿæœ€ä½çš„èŠ‚ç‚¹ï¼›æµ‹è¯•åå®¹å·®å¤§äº 50ms æ‰ä¼šåˆ‡æ¢åˆ°å»¶è¿Ÿä½çš„é‚£ä¸ªèŠ‚ç‚¹ï¼›ç­›é€‰å‡ºâ€œé¦™æ¸¯â€èŠ‚ç‚¹ï¼Œæ”¯æŒæ­£åˆ™è¡¨è¾¾å¼
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: url-test, tolerance: 50, use: [ğŸ›« æœºåœºè®¢é˜… 1, ğŸ›« æœºåœºè®¢é˜… 2], filter: "(?i)(ğŸ‡­ğŸ‡°|æ¸¯|hk|hongkong|hong kong)"}
  # èŠ‚ç‚¹è‡ªåŠ¨å›é€€ï¼Œé»˜è®¤é€‰æ‹©ç¬¬ä¸€ä¸ªèŠ‚ç‚¹ï¼ŒèŠ‚ç‚¹è¶…æ—¶ååˆ™ä¼šæŒ‰ä»£ç†é¡ºåºé€‰æ‹©ä¸‹ä¸€ä¸ªå¯ç”¨èŠ‚ç‚¹ï¼Œä»¥æ­¤ç±»æ¨ã€‚ä¹Ÿè¢«å«åšâ€œæ•…éšœè½¬ç§»â€
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, type: fallback, use: [ğŸ›« æœºåœºè®¢é˜… 1, ğŸ›« æœºåœºè®¢é˜… 2], filter: "(?i)(ğŸ‡¹ğŸ‡¼|å°|tw|taiwan|tai wan)"}
  # èŠ‚ç‚¹è´Ÿè½½å‡è¡¡ï¼Œå³å°†è¯·æ±‚å‡åŒ€åˆ†é…åˆ°å¤šä¸ªèŠ‚ç‚¹ä¸Šï¼Œä¼˜ç‚¹æ˜¯æ›´ç¨³å®šï¼Œé€Ÿåº¦å¯èƒ½æœ‰æå‡ï¼›å°†ç›¸åŒé¡¶çº§åŸŸåçš„è¯·æ±‚åˆ†é…ç»™ç­–ç•¥ç»„å†…çš„åŒä¸€ä¸ªä»£ç†èŠ‚ç‚¹ï¼›æ¨èåœ¨èŠ‚ç‚¹å¤ç”¨æ¯”è¾ƒå¤šçš„æƒ…å†µä¸‹ä½¿ç”¨
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: load-balance, strategy: consistent-hashing, use: [ğŸ›« æœºåœºè®¢é˜… 1, ğŸ›« æœºåœºè®¢é˜… 2], filter: "(?i)(ğŸ‡¯ğŸ‡µ|æ—¥|jp|japan)"}
  # å¯ä½¿ç”¨ `include-all: true` ä»£æ›¿ `use: [ğŸ›« æœºåœºè®¢é˜… 1, ğŸ›« æœºåœºè®¢é˜… 2, ...]`ï¼Œæ„æ€ä¸ºå¼•å…¥æ‰€æœ‰å‡ºç«™ä»£ç†ä»¥åŠä»£ç†é›†åˆ
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, type: url-test, tolerance: 50, include-all: true, filter: "(?i)(ğŸ‡¸ğŸ‡¬|æ–°|sg|singapore)"}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, type: url-test, tolerance: 100, use: [ğŸ›« æœºåœºè®¢é˜… 1, ğŸ›« æœºåœºè®¢é˜… 2], filter: "(?i)(ğŸ‡ºğŸ‡¸|ç¾|us|unitedstates|united states)"}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, tolerance: 100, include-all: true}
  - {name: ğŸ‘‰ æ‰‹åŠ¨é€‰æ‹©, type: select, include-all: true}

# è§„åˆ™é›†ï¼ˆyaml æ–‡ä»¶æ¯å¤©è‡ªåŠ¨æ›´æ–°ï¼‰
rule-providers:
  ads:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/ads.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ads.mrs"
    interval: 86400

  private:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/private.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/private.mrs"
    interval: 86400

  trackerslist:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/trackerslist.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/trackerslist.mrs"
    interval: 86400

  # è‹¥ä½¿ç”¨ ShellCrashï¼Œç”±äºæ— æ³•åˆ¤æ–­æœ¬æœºè¿›ç¨‹ï¼ˆé»˜è®¤ `find-process-mode: off`ï¼‰ï¼Œéœ€åˆ é™¤æ­¤æ¡ `applications`
  applications:
    type: http
    behavior: classical
    format: text
    path: ./ruleset/applications.list
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/applications.list"
    interval: 86400

  microsoft-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/microsoft-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/microsoft-cn.mrs"
    interval: 86400

  apple-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/apple-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/apple-cn.mrs"
    interval: 86400

  google-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/google-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/google-cn.mrs"
    interval: 86400

  games-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/games-cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games-cn.mrs"
    interval: 86400

  media:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/media.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/media.mrs"
    interval: 86400

  games:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/games.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games.mrs"
    interval: 86400

  ai:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/ai.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ai.mrs"
    interval: 86400

  networktest:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/networktest.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/networktest.mrs"
    interval: 86400

  proxy:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/proxy.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/proxy.mrs"
    interval: 86400

  cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cn.mrs"
    interval: 86400

  privateip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/privateip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/privateip.mrs"
    interval: 86400

  cnip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/cnip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cnip.mrs"
    interval: 86400

  mediaip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/mediaip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/mediaip.mrs"
    interval: 86400

  gamesip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/gamesip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/gamesip.mrs"
    interval: 86400

  telegramip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/telegramip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/telegramip.mrs"
    interval: 86400

# è§„åˆ™
rules:
  # è‡ªå®šä¹‰è§„åˆ™ä¼˜å…ˆæ”¾å‰é¢
  - RULE-SET,private,ğŸ”’ ç§æœ‰ç½‘ç»œ
  - RULE-SET,ads,ğŸ›‘ å¹¿å‘ŠåŸŸå
  - RULE-SET,trackerslist,ğŸ“‹ Trackerslist
  # ä¸ºäº†ä½¿ P2P æµé‡ï¼ˆBT ä¸‹è½½ï¼‰èµ°ç›´è¿ï¼Œå¯æ·»åŠ ä¸€æ¡ `DST-PORT` è§„åˆ™ï¼ˆShellCrash ä¼šé»˜è®¤å¯ç”¨â€œåªä»£ç†å¸¸ç”¨ç«¯å£â€ï¼Œå¯åˆ é™¤æ­¤æ¡ `DST-PORT`ï¼‰
  - DST-PORT,6881-6889,ğŸ¯ å…¨çƒç›´è¿
  # è‹¥ä½¿ç”¨ ShellCrashï¼Œç”±äºæ— æ³•åˆ¤æ–­æœ¬æœºè¿›ç¨‹ï¼ˆé»˜è®¤ `find-process-mode: off`ï¼‰ï¼Œéœ€åˆ é™¤æ­¤æ¡ `RULE-SET`
  - RULE-SET,applications,â¬‡ï¸ ç›´è¿è½¯ä»¶
  - RULE-SET,microsoft-cn,ğŸªŸ å¾®è½¯æœåŠ¡
  - RULE-SET,apple-cn,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,google-cn,ğŸ‡¬ è°·æ­ŒæœåŠ¡
  - RULE-SET,games-cn,ğŸ® æ¸¸æˆæœåŠ¡
  - RULE-SET,media,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,games,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,ai,ğŸ¤– AI å¹³å°
  - RULE-SET,networktest,ğŸ“ˆ ç½‘ç»œæµ‹è¯•
  - RULE-SET,proxy,ğŸ§± ä»£ç†åŸŸå
  - RULE-SET,cn,ğŸ›¡ï¸ ç›´è¿åŸŸå
  - RULE-SET,privateip,ğŸ”’ ç§æœ‰ç½‘ç»œ,no-resolve
  - RULE-SET,cnip,ğŸ€„ï¸ ç›´è¿ IP
  - RULE-SET,mediaip,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,gamesip,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,telegramip,ğŸ“² ç”µæŠ¥æ¶ˆæ¯,no-resolve
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
