# ç­–ç•¥ç»„
proxy-groups:
  # é»˜è®¤é€‰æ‹©æ–°åŠ å¡èŠ‚ç‚¹
  - {name: ğŸ¥ å¥ˆé£è§†é¢‘, type: select, proxies: [ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹]}
  # é»˜è®¤é€‰æ‹©æ—¥æœ¬èŠ‚ç‚¹ï¼Œä¹Ÿå¯åˆ‡æ¢åˆ°ç›´è¿
  - {name: ğŸ“º å“”å“©å“”å“©, type: select, proxies: [ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ¯ å…¨çƒç›´è¿]}
  # è‡ªåŠ¨é€‰æ‹©å»¶è¿Ÿæœ€ä½çš„æ–°åŠ å¡èŠ‚ç‚¹ï¼›å®¹å·®å¤§äº 50ms æ‰ä¼šåˆ‡æ¢åˆ°å»¶è¿Ÿä½çš„é‚£ä¸ªèŠ‚ç‚¹
  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, type: url-test, tolerance: 50, include-all: true, filter: "(?i)(ğŸ‡¸ğŸ‡¬|æ–°|sg|singapore)"}
  # æ‰‹åŠ¨é€‰æ‹©æ—¥æœ¬ä»»ä¸€èŠ‚ç‚¹
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(ğŸ‡¯ğŸ‡µ|æ—¥|jp|japan)"}
  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [DIRECT], hidden: true}

# è§„åˆ™é›†ï¼ˆyaml æ–‡ä»¶æ¯å¤©è‡ªåŠ¨æ›´æ–°ï¼‰
rule-providers:
  netflix:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/netflix.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/netflix.mrs"
    interval: 86400

  netflixip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/netflixip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/netflixip.mrs"
    interval: 86400

  bilibili:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/bilibili.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/bilibili.mrs"
    interval: 86400

# è§„åˆ™
rules:
  # è‡ªå®šä¹‰è§„åˆ™ä¼˜å…ˆæ”¾å‰é¢
  - RULE-SET,netflix,ğŸ¥ å¥ˆé£è§†é¢‘
  - RULE-SET,netflixip,ğŸ¥ å¥ˆé£è§†é¢‘
  - RULE-SET,bilibili,ğŸ“º å“”å“©å“”å“©
