port: 3333

# å•ä¸ªèŠ‚ç‚¹
proxies:  

# æœºåœºé…ç½®æ¨¡å—
provider_config: &provider_config {"type": "http","interval": 86400,"user-agent": "clash","health-check": {"enable": true,"url": "http://www.apple.com/library/test/success.html","interval": 300}}

proxy-providers:
  # ç¬¬ä¸€ä¸ªæœºåœº
  AP1:
    url: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx #ä¿®æ”¹ä½ çš„æœºåœº1è®¢é˜…åœ°å€
    <<: *provider_config
    override:
      additional-prefix: "[AP1]"
  # ç¬¬äºŒä¸ªæœºåœº
  # AP2:
  #   url: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx #ä¿®æ”¹ä½ çš„æœºåœº2è®¢é˜…åœ°å€
  #   <<: *provider_config
  #   override:
  #     additional-prefix: "[AP2]"
  # ç¬¬ä¸‰ä¸ªæœºåœº
  # AP3:
  #   url: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx #ä¿®æ”¹ä½ çš„æœºåœº3è®¢é˜…åœ°å€
  #   <<: *provider_config
  #   override:
  #     additional-prefix: "[AP3]"
      

# åˆ†ç»„é…ç½®æ¨¡å—
standard_proxies: &standard_proxies {"type": "select", "proxies": ["ğŸ”ƒ è‡ªåŠ¨é€‰æ‹©", "ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹", "ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹", "ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹", "ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹", "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹", "ğŸŒ å…¶ä»–èŠ‚ç‚¹", "DIRECT"], "include-all": true}

# èŠ‚ç‚¹é…ç½®æ¨¡å—
filter_proxies: &filter_proxies {"type": "url-test", "url": "http://www.apple.com/library/test/success.html", "interval": 300, "tolerance": 100, "include-all": true}

proxy-groups:
  - name: ğŸ¤– ChatGPT
    <<: *standard_proxies

  - name: ğŸ¥ YouTube
    <<: *standard_proxies  
      
  - name: ğŸ¥ Emby
    <<: *standard_proxies

  - name: ğŸ¥ TikTok
    <<: *standard_proxies
    
  - name: ğŸ¥ bilibili
    <<: *standard_proxies

  - name: ğŸ¥ APTV
    <<: *standard_proxies
      
  - name: ğŸ¥ Netflix
    <<: *standard_proxies

  - name: ğŸ¥ Disney+
    <<: *standard_proxies

  - name: ğŸ“² Telegram
    <<: *standard_proxies
      
  - name: ğŸ“² Twitter
    <<: *standard_proxies

  - name: ğŸ“² Instagram
    <<: *standard_proxies

  - name: ğŸ“² Facebook
    <<: *standard_proxies

  - name: ğŸµ Spotify
    <<: *standard_proxies

  - name: â±ï¸ Speedtest
    <<: *standard_proxies

  - name: ğŸ” GitHub
    <<: *standard_proxies

  - name: ğŸ” Google
    <<: *standard_proxies

  - name: ğŸ Apple
    <<: *standard_proxies

  - name: ğŸ’» Microsoft
    <<: *standard_proxies

  - name: ğŸ®Steam
    <<: *standard_proxies

  - name: ğŸ® Xbox
    <<: *standard_proxies

  - name: ğŸ® PlayStation
    <<: *standard_proxies

  - name: ğŸ® Nintendo
    <<: *standard_proxies

  - name: ğŸ” Porn
    <<: *standard_proxies
    
  - name: ğŸŒ å›½å¤–ç½‘ç«™
    <<: *standard_proxies

  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    <<: *standard_proxies

  - name: ğŸ”ƒ è‡ªåŠ¨é€‰æ‹©
    <<: *filter_proxies
    
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
    <<: *filter_proxies
    filter: '^(?=.*((?i)ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|United States)\b))).*$'

  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    <<: *filter_proxies
    filter: '^(?=.*((?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|Hong)\b))).*$'

  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    <<: *filter_proxies
    filter: '^(?=.*((?i)ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|(\b(JP|Japan)\b))).*$'

  - name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
    <<: *filter_proxies
    filter: '^(?=.*((?i)ğŸ‡¹ğŸ‡¼|TW|å°æ¹¾)).*$'

  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
    <<: *filter_proxies
    filter: '^(?=.*((?i)ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|(\b(SG|Singapore)\b))).*$'
      
  - name: ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹
    <<: *filter_proxies
    filter: '^(?=.*((?i)ğŸ‡¬ğŸ‡§|è‹±å›½|ä¼¦æ•¦|(\b(UK|United Kingdom)\b))).*$'

  - name: ğŸŒ å…¶ä»–èŠ‚ç‚¹
    <<: *filter_proxies
    filter: '^(?!.*(ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States|ğŸ‡­ğŸ‡°|é¦™æ¸¯|HK|Hong|ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|JP|Japan|ğŸ‡¹ğŸ‡¼|å°æ¹¾|TW|ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|SG|Singapore|ğŸ‡¬ğŸ‡§|è‹±å›½|ä¼¦æ•¦|UK|United Kingdom)).*$'

# ruleSeté…ç½®æ¨¡å—
rule-anchor:
  ip: &ip {type: http, interval: 43200, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 43200, behavior: domain, format: mrs}
rule-providers:
  bilibili:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs

  cn:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs

  tiktok:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs

  emby:
    <<: *domain
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/Emby.mrs
  
  netflix:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs
  
  disney:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.mrs

  spotify:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs

  speedtest:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/speedtest.mrs
  
  github:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs

  telegram:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs

  youtube:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs

  google:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs

  twitter:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs

  instagram:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/instagram.mrs

  facebook:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/facebook.mrs

  steam@cn:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam@cn.mrs

  steam:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs

  apple:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs

  microsoft@cn:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft@cn.mrs

  microsoft:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs

  xbox:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/xbox.mrs

  playstation:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/playstation.mrs

  nintendo@cn:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/nintendo@cn.mrs

  nintendo:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/nintendo.mrs

  category-porn:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.mrs

  openai:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.mrs

  geolocation-!cn:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs

  private_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/private.mrs

  apple_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs

  google_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/google.mrs

  telegram_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/telegram.mrs

  netflix_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/netflix.mrs

  twitter_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/twitter.mrs

  emby_ip:
    <<: *ip
    url: https://github.com/666OS/rules/raw/release/mihomo/ip/Emby.mrs

  cn_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/cn.mrs

rules:
  # ğŸ¥ bilibili
  - RULE-SET,bilibili,ğŸ¥ bilibili
  # å›½å†…ç½‘ç«™
  - RULE-SET,cn,DIRECT
  # ğŸ¥ TikTok
  - RULE-SET,tiktok,ğŸ¥ TikTok
  # ğŸ¥ Emby
  - RULE-SET,emby,ğŸ¥ Emby
  # ğŸ¥ aptv
  - IP-CIDR,148.135.93.213/32,ğŸ¥ APTV,no-resolve
  # ğŸ¥ Netflix
  - RULE-SET,netflix,ğŸ¥ Netflix
  # ğŸ¥ Disney+
  - RULE-SET,disney,ğŸ¥ Disney+
  # ğŸµ Spotify
  - RULE-SET,spotify,ğŸµ Spotify
  # â±ï¸ Speedtest
  - RULE-SET,speedtest,â±ï¸ Speedtest
  # ğŸ” GitHub
  - RULE-SET,github,ğŸ” GitHub
  # ğŸ“² Telegram
  - RULE-SET,telegram,ğŸ“² Telegram
  # ğŸ¥ YouTube
  - RULE-SET,youtube,ğŸ¥ YouTube
  # ğŸ” Google
  - RULE-SET,google,ğŸ” Google
  # ğŸ“² Twitter
  - RULE-SET,twitter,ğŸ“² Twitter
  # ğŸ“² Instagram
  - RULE-SET,instagram,ğŸ“² Instagram
  # ğŸ“² Facebook
  - RULE-SET,facebook,ğŸ“² Facebook
  # ğŸ®Steam
  - RULE-SET,steam@cn,DIRECT
  - RULE-SET,steam,ğŸ®Steam
  # ğŸ Apple
  - RULE-SET,apple,ğŸ Apple
  # ğŸ’» Microsoft
  - RULE-SET,microsoft@cn,DIRECT
  - RULE-SET,microsoft,ğŸ’» Microsoft
  # ğŸ® Xbox
  - RULE-SET,xbox,ğŸ® Xbox
  # ğŸ® PlayStation
  - RULE-SET,playstation,ğŸ® PlayStation
  # ğŸ® Nintendo
  - RULE-SET,nintendo@cn,DIRECT
  - RULE-SET,nintendo,ğŸ® Nintendo
  # ğŸ” Porn
  - RULE-SET,category-porn,ğŸ” Porn
  # ğŸ¤– ChatGPT
  - RULE-SET,openai,ğŸ¤– ChatGPT
  # ğŸŒ å›½å¤–ç½‘ç«™
  - RULE-SET,geolocation-!cn,ğŸŒ å›½å¤–ç½‘ç«™
  # private_ip
  - RULE-SET,private_ip,DIRECT,no-resolve
  # apple_ip
  - RULE-SET,apple_ip,ğŸ Apple
  # google_ip
  - RULE-SET,google_ip,ğŸ” Google
  # telegram_ip
  - RULE-SET,telegram_ip,ğŸ“² Telegram
  # netflix_ip
  - RULE-SET,netflix_ip,ğŸ¥ Netflix
  # twitter_ip
  - RULE-SET,twitter_ip,ğŸ“² Twitter
  # emby_ip
  - RULE-SET,emby_ip,ğŸ¥ Emby
  # cn_ip
  - RULE-SET,cn_ip,DIRECT
  # ğŸŸ æ¼ç½‘ä¹‹é±¼
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
